version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "rust"
enabled = true

[[analyzers]]
name = "shell"
enabled = true